# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20171110_1802'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='assignment',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ManyToManyField(to='course.AssignmentMaterial'),
        ),
    ]
