# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-18 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_field',
            field=models.IntegerField(default=1944),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='width_field',
            field=models.IntegerField(default=2592),
        ),
    ]
