# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-18 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_userprofile_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='width_field',
        ),
    ]
