# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20171112_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_no',
            field=models.ManyToManyField(to='course.course'),
        ),
    ]
