# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='elective',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='course',
            name='offered_to',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
