# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20171110_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesInSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_electives', models.IntegerField(null=True)),
                ('number_of_core', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.AddField(
            model_name='coursesinsemester',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.OfferedIn', to_field='semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='offered_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.OfferedIn'),
        ),
    ]
